version: '3'
services:

  web:
    container_name: bob-app
    build:
      context: bitmexOrderBook
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo
      - redis

  redis:
    container_name: bob-redis
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    restart: always

  mongo:
    container_name: bob-mongo
    image: mongo
    ports:
      - "27017:27017"
