version: '3'
services:

  web:
    container_name: bob-python
    build:
      context: bitmexOrderBook
      dockerfile: Dockerfile
    volumes:
      - .:/bitmexOrderBook
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped

  redis:
    container_name: bob-redis
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongodb:
    restart: unless-stopped
    image: mongo
